// 
// NHibernate.Mapping.Attributes
// This product is under the terms of the GNU Lesser General Public License.
//
//
//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version: 2.0.50727.x
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------
//
//
// This source code was auto-generated by Refly, Version=2.21.1.0 (modified).
//
namespace NHibernate.Mapping.Attributes
{
	
	
	/// <summary> </summary>
	[System.AttributeUsage(System.AttributeTargets.Property | System.AttributeTargets.Field, AllowMultiple=true)]
	[System.Serializable()]
	public class FilterDefAttribute : BaseAttribute
	{
		
		private string _condition = null;
		
		private bool _usemanytoonespecified;
		
		private string _content = null;
		
		private bool _usemanytoone = true;
		
		private string _name = null;
		
		/// <summary> Default constructor (position=0) </summary>
		public FilterDefAttribute() : 
				base(0)
		{
		}
		
		/// <summary> Constructor taking the position of the attribute. </summary>
		public FilterDefAttribute(int position) : 
				base(position)
		{
		}
		
		/// <summary> </summary>
		public virtual string Name
		{
			get
			{
				return this._name;
			}
			set
			{
				this._name = value;
			}
		}
		
		/// <summary> </summary>
		public virtual string Condition
		{
			get
			{
				return this._condition;
			}
			set
			{
				this._condition = value;
			}
		}
		
		/// <summary> </summary>
		public virtual bool UseManyToOne
		{
			get
			{
				return this._usemanytoone;
			}
			set
			{
				this._usemanytoone = value;
				_usemanytoonespecified = true;
			}
		}
		
		/// <summary> Tells if UseManyToOne has been specified. </summary>
		public virtual bool UseManyToOneSpecified
		{
			get
			{
				return this._usemanytoonespecified;
			}
		}
		
		/// <summary> Gets or sets the content of this element </summary>
		public virtual string Content
		{
			get
			{
				return this._content;
			}
			set
			{
				this._content = value;
			}
		}
	}
}
